# Generated by Django 4.0.6 on 2023-01-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_model', models.TextField(max_length=100)),
                ('vehicle_des', models.TextField(max_length=200)),
            ],
        ),
    ]
