# Generated by Django 4.0.6 on 2023-01-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_des',
            field=models.TextField(max_length=2000),
        ),
    ]
